openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: answer-controller
    description: Answer Controller
  - name: quotes-controller
    description: Quotes Controller
  - name: words-controller
    description: Words Controller
paths:
  /answer:
    post:
      tags:
        - answer-controller
      summary: askMagicEightBall
      operationId: askMagicEightBallUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Answer'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /quote:
    get:
      tags:
        - quotes-controller
      summary: getRandomQuote
      operationId: getRandomQuoteUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Quotes'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /word:
    get:
      tags:
        - words-controller
      summary: getRandomWord
      operationId: getRandomWordUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Words'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    Answer:
      title: Answer
      type: object
      properties:
        answer:
          type: string
        id:
          type: integer
          format: int32
        question:
          type: string
    Quotes:
      title: Quotes
      type: object
      properties:
        author:
          type: string
        id:
          type: integer
          format: int32
        quote:
          type: string
    Words:
      title: Words
      type: object
      properties:
        def:
          type: string
        id:
          type: integer
          format: int32
        origin:
          type: string
        used:
          type: string
        word:
          type: string
